#!/bin/bash

useradd -d /home/bohdan -m -s/bin/bash \
-c FullName,Phone,OtherInfo bohdan && echo bohdan:your-pass | chpasswd
usermod -aG sudo bohdan
su - bohdan -c "mkdir -p /home/bohdan/.ssh && cd .ssh && ssh-keygen -f bohdan -P 6BWALz7TbU"
su - bohdan -c "cd /home/bohdan/.ssh && cat bohdan.pub >> /home/bohdan/.ssh/authorized_keys"
echo "User bohdan and ssh-key was added"

sed -i 's/PermitRootLogin yes/PermitRootLogin no/g' /etc/ssh/sshd_config
sed -i 's/PasswordAuthentication yes/PasswordAuthentication no/g' /etc/ssh/sshd_config
sed -i '1d' /etc/passwd && echo 'root:x:0:0:root:/root:/sbin/nologin' >> /etc/passwd
systemctl restart sshd
echo "Root login deactivated"
