#!/bin/bash
menu() {
        echo "-=-=-=-=-=-=-=-=-=-=-=-backup by Kanarskyi Bohdan-=-=-=-=-=-=-=-=-=-=-=-"
        cat <<EOF
Usage: ./backup [SOURCE] [DESTINATION]
SOURCE:
   for example:
DESTINATION:
   for example:
EOF
}

if [ -n "$1" ]
then
case "$1" in

*) menu ;;
esac
shift
else menu
fi
