#!/bin/bash
menu() {
        echo "-=-=-=-=-=-=-=-=-=-=-=-TCP/IP scan by Kanarskyi Bohdan-=-=-=-=-=-=-=-=-=-=-=-"
        cat <<EOF
Usage: ./scan [OPTIONS]
OPTIONS:
  --all, -a:
        Displays the IP addresses of all hosts in the current subnet
  --target, -t [IP] [PORT]:
        Displays a list of open system TCP ports
EOF
}

scan_port() {
        echo "-------------------Scanning port---------------------"
        if [ -n "$2" ] && [ -n "$3" ]
        then
        nc -nvz $2 $3
        elif [ -z "$3" ]
        then
        nc -nvz $2 1-65535 2>&1 | grep succeeded
        fi
        echo "-----------------------DONE--------------------------"
}

show_ip() {
        echo "-----------------------------------------------------"
        echo "             This server has next ip:          "
        ip -4 a | grep inet | cut -f1 | awk '{print $2}' | cut -f1,2,3
        echo "-----------------------------------------------------"
}

if [ -n "$1" ]
then
case "$1" in
-a | --all) show_ip $* ;;
-t | --target) scan_port $* ;;
*) menu ;;
esac
shift
else menu
fi
